import { Application, Scene } from "playcanvas-extended";
import { serializableClassDeclarationCustom } from "simple-typed-serialization";

serializableClassDeclarationCustom(
    Scene,
    {
        preDeserializer: () => new Scene(Application.getApplication()!.graphicsDevice)
    },
    "ambientBake",
    "ambientBakeNumSamples",
    "ambientBakeOcclusionBrightness",
    "ambientBakeOcclusionContrast",
    "ambientBakeSpherePart",
    "ambientLight",
    "ambientLuminance",
    "clusteredLightingEnabled",
    "envAtlas",
    "exposure",
    "fog",
    "fogColor",
    "fogDensity",
    "fogStart",
    "fogEnd",
    "gammaCorrection",
    // "layers",
    "lighting",
    "lightmapFilterEnabled",
    "lightmapFilterRange",
    "lightmapFilterSmoothness",
    "lightmapHDR",
    "lightmapMaxResolution",
    "lightmapMode",
    "lightmapPixelFormat",
    "lightmapSizeMultiplier",
    "physicalUnits",
    "root",
    "sky",
    "skybox",
    "skyboxIntensity",
    "skyboxLuminance",
    "skyboxMip",
    "skyboxRotation",
    "toneMapping",
)